name: Localization CD

on:
  push:
    branches:
      - main
    paths:
      - 'localization.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload to server
        uses: wei/curl@v1.1.1
        with:
          args: |
            -F 'localization=@localization.json' \
            https://${{ secrets.SSH_HOST }}/uploadlum.php
      
      - name: Running remote script
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            python3 ~/downloadLocalization.py localization.json

          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}